version: '3'
services:
  auth:
    build: auth/
    ports:
      - "5000:5000"
    depends_on:
      - redis
  point:
    build: point/
    depends_on:
      - redis
      - db
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: "redis:alpine"
  jaeger:
    image: "jaegertracing/all-in-one:0.8.0"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
